#!/usr/bin/env node
// Fetch real farmland polygons near the Lane County demo field from the
// OpenStreetMap Overpass API and bake them into src/data/parcels.ts as a
// static fixture (no runtime network dependency).
//
//   node scripts/fetch-parcels.mjs [cached-overpass.json]
//
// Geometry is REAL (© OpenStreetMap contributors, ODbL — credited via the
// map's OSM attribution); names/tones are assigned deterministically here.
// Re-run to refresh; output is capped at the 20 largest parcels.

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'src/data/parcels.ts');
// Centered on the river-bottom farm belt between Santa Clara and Coburg —
// a tight radius keeps the 20 parcels clustered so the default map view can
// open close-in instead of spanning the whole metro.
const CENTER = { lat: 44.105, lng: -123.065 };
const RADIUS_M = 4500;
const MAX_PARCELS = 20;
const MAX_VERTICES = 48;

const QUERY = `[out:json][timeout:50];way["landuse"="farmland"](around:${RADIUS_M},${CENTER.lat},${CENTER.lng});out geom 30;`;

async function load() {
  const cached = process.argv[2];
  if (cached && existsSync(cached)) {
    console.log(`Using cached Overpass response: ${cached}`);
    return JSON.parse(readFileSync(cached, 'utf8'));
  }
  console.log('Querying Overpass…');
  const res = await fetch('https://overpass-api.de/api/interpreter', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'biochar-atlas-design/0.1 (ESA design spoke)',
    },
    body: `data=${encodeURIComponent(QUERY)}`,
  });
  if (!res.ok) throw new Error(`Overpass ${res.status}`);
  return res.json();
}

/** Shoelace area in acres for a [lng,lat] ring (local-meter projection). */
function acresOf(ring) {
  const lat0 = (CENTER.lat * Math.PI) / 180;
  const pts = ring.map(([lng, lat]) => [lng * 111320 * Math.cos(lat0), lat * 110540]);
  let area = 0;
  for (let i = 0; i < pts.length - 1; i++) {
    area += pts[i][0] * pts[i + 1][1] - pts[i + 1][0] * pts[i][1];
  }
  return Math.abs(area / 2) * 0.000247105;
}

/** Keep at most MAX_VERTICES points (plus closure). */
function simplify(ring) {
  if (ring.length <= MAX_VERTICES) return ring;
  const step = Math.ceil(ring.length / MAX_VERTICES);
  const out = ring.filter((_, i) => i % step === 0);
  const first = out[0];
  const last = out[out.length - 1];
  if (first[0] !== last[0] || first[1] !== last[1]) out.push(first);
  return out;
}

const data = await load();
const ways = (data.elements ?? []).filter((e) => e.type === 'way' && e.geometry?.length >= 4);

const parcels = ways
  .map((w) => {
    let ring = w.geometry.map((g) => [
      Math.round(g.lon * 1e5) / 1e5,
      Math.round(g.lat * 1e5) / 1e5,
    ]);
    const first = ring[0];
    const last = ring[ring.length - 1];
    if (first[0] !== last[0] || first[1] !== last[1]) ring.push(first);
    ring = simplify(ring);
    return { osmId: w.id, ring, acres: Math.round(acresOf(ring) * 10) / 10 };
  })
  .filter((p) => p.acres >= 2) // skip slivers
  .sort((a, b) => b.acres - a.acres)
  .slice(0, MAX_PARCELS)
  .map((p, i) => ({ ...p, id: `parcel-${String(i + 1).padStart(2, '0')}`, tone: i % 8 }));

const ts = `// =============================================================================
// REAL GEOMETRY, MOCK ATTRIBUTES — generated by scripts/fetch-parcels.mjs.
// Polygons are actual OpenStreetMap landuse=farmland ways within ${RADIUS_M / 1000} km of the
// Lane County demo field (© OpenStreetMap contributors, ODbL — the map's OSM
// attribution covers this). Acreage is computed from the geometry; ids and
// tone indices are assigned here. Re-run the script to refresh. Do not edit
// by hand.
// =============================================================================

export interface Parcel {
  id: string;
  /** OSM way id the geometry came from. */
  osmId: number;
  /** Computed from the polygon (shoelace, local-meter projection). */
  acres: number;
  /** Index into the parchment patchwork palette (see suitability-tool map). */
  tone: number;
  /** GeoJSON-style closed ring, [lng, lat] order. */
  ring: number[][];
}

export const parcels: Parcel[] = ${JSON.stringify(
  parcels.map(({ id, osmId, acres, tone, ring }) => ({ id, osmId, acres, tone, ring })),
  null,
  2,
)};
`;

writeFileSync(OUT, ts);
console.log(`Wrote ${parcels.length} parcels → ${OUT}`);
console.log(
  parcels.map((p) => `${p.id} ${p.acres} ac (${p.ring.length} pts, osm ${p.osmId})`).join('\n'),
);
